### ISSUE TITLE
Trying to run a new keeper getting error

### ISSUE THREAD

**Issue by jruffer** [perpfutui/apex-graph#1]
$ brownie run keeper
Brownie v1.16.4 - Python development framework for Ethereum

ApexKeeperProject is the active project.
could not find telegram library
env variables not available

Running 'scripts/keeper.py::main'...
Enter password for "BOT": 
2021-12-22 11:18:11,421 getting amms ser
2021-12-22 11:18:12,582 Connected with: 0xF6f86B6f29651d3Aa9ab50b8B0B908319E0c8fBB
2021-12-22 11:18:13,124 getting teh orders SER
  File "brownie/_cli/run.py", line 50, in main
    args["<filename>"], method_name=args["<function>"] or "main", _include_frame=True
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/keeper.py", line 104, in main
    orders = get_orders(assets)
  File "./scripts/order_executor.py", line 70, in get_orders
    output.append(Order(assets,**order))
  File "./scripts/class_order.py", line 29, in __init__
    self.asset = next(x for x in assets if x.address.lower() == asset.lower())
StopIteration: 
I've tracked this to order_executor.py file that contains lines like these:
PERP_SUBGRAPH = "https://api.thegraph.com/subgraphs/name/perpetual-protocol/perp-position-subgraph"
APEX_SUBGRAPH = "https://api.thegraph.com/subgraphs/name/abdullathedruid/apex-keeper"

**Comment by jruffer** [comment]
Keeper is no longer a good option.  Look at chronos bots instead.

**Comment by abdullathedruid** [comment]
For reference for anybody reading this, we archived the repo back in May and no longer support this.
We would recommend/advise looking at this repo https://github.com/perpfutui/chronos_bot instead
